parent-scalar-a: true
parent-scalar-b: true
parent-scalar-c: true

parent-mapping-child-mapping:
  a: "parent"
  b: "parent"
parent-mapping-child-mapping-replaces:
  a: "parent"
  b: "parent"
parent-mapping-child-sequence:
  a: "parent"
  b: "parent"

parent-mapping-child-mapping-nested:
  nested:
    a: "parent"
    b: "parent"

parent-list-child-list:
  - 1
  - 2
parent-list-child-list-extends:
  - 1
  - 2
parent-list-child-mapping:
  - 1
  - 2

parent-list-joinable:
  - id: foo
    a: "parent"
  - id: bar
    b: "parent"

parent-list-joinable-recursive:
  - id: foo
    a: "parent"
    b: "parent"
    obj:
      - id: baz
        a: "parent"
        b: "parent"
  - id: bar
    a: "parent"
