parent-scalar-a: true
parent-scalar-b: true
parent-scalar-c: true

parent-mapping-a:
  a: 1
  b: 2
parent-mapping-b:
  a: 1
  b: 2
parent-mapping-c:
  a: 1
  b: 2

parent-nested-mapping-a:
  inner:
    a: 1

parent-list-a:
  - 1
  - 2
parent-list-b:
  - 1
  - 2
parent-list-c:
  - 1
  - 2

parent-joinable:
  - id: foo
    a: 1
  - id: bar
    b: 2
